name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Smiley Sans
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Build fonts
        run: source build.sh dev
      - uses: actions/upload-artifact@v4
        with:
          name: smiley-sans
          path: |
            build/*.otf
            build/*.ttf
            build/*.woff2
